include:
  - project: 'IsyFact/isy-gitlabci-templates'
    file: '/maven/.gitlab-ci-maven.yml'

variables:
  MAVEN_CLI_OPTS: -Dinternalnodenpm=true

build:
  extends: .maven-build

build:doc:
  extends: .maven-build
  variables:
    MAVEN_CLI_OPTS: -Pbuild-documentation -Dskip.npm -Dskip.grunt -Dskip.installnodenpm
  artifacts:
    expire_in: 1 day
    paths:
      - '**/target/doc/**'

test:
  extends: .maven-test

package:
  extends: .maven-package

deploy:deploy-manual:
  extends: .maven-deploy-manual

deploy:
  extends: .maven-deploy

stages:
  - build
  - test
  - package
  - deploy
