name: Build Maven
on:
  pull_request:
    branches:
      - master
      - 'release/**'
  push:
    branches:
      - master
      - 'release/**'

jobs:
  Version:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/next_version.yml@v1.7.0

  Maven:
    needs: [Version]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_build_template.yml@v1.7.0
    with:
      jdk-version: 8
      maven-opts: '-s ./.github/settings.xml -pl !isy-web-doc -Dskip.js.tests=true'
      checkout-lfs: true
      version: ${{ needs.Version.outputs.next-version }}
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

  DeployGitHubPackages:
    if: github.event_name == 'push'
    needs: [Version, Maven]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_deploy_template.yml@v1.7.0
    with:
      version: ${{ needs.Version.outputs.next-version }}
      checkout-lfs: true
      maven-opts: '-s ./.github/settings.xml -pl !isy-web-doc -Dskip.js.tests=true'
      deploy-url-snapshot: 'https://maven.pkg.github.com/IsyFact/isy-web'
    secrets:
      DEPLOY_SERVER_USER_NAME: ${{ github.actor }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
