name: Build Maven
on:
  pull_request:
    branches:
      - master
      - 'release/**'
  push:
    branches:
      - master
      - 'release/**'

jobs:
  Version:
    uses: IsyFact/isyfact-standards/.github/workflows/next_version.yml@master
    with:
      next-version: 7.0.0

  Maven:
    needs: [Version]
    uses: IsyFact/isyfact-standards/.github/workflows/maven_build_template.yml@master
    with:
      maven-opts: '-pl isy-web-lib -Dskip.js.tests=true'
      checkout-lfs: true
      version: ${{ needs.Version.outputs.next-version }}