name: Build Maven
on:
  pull_request:
    branches:
      - master
      - 'release/**'
  push:
    branches:
      - master
      - 'release/**'

jobs:
  Version:
    uses: IsyFact/isyfact-standards/.github/workflows/next_version.yml@master

  Maven:
    needs: [Version]
    uses: IsyFact/isyfact-standards/.github/workflows/maven_build_template.yml@master
    with:
      maven-opts: '-s ./.github/settings.xml -pl isy-web-lib -Dskip.js.tests=true'
      checkout-lfs: true
      version: ${{ needs.Version.outputs.next-version }}

  Snapshot:
    if: github.event_name == 'push'
    needs: [Version, Maven]
    uses: IsyFact/isyfact-standards/.github/workflows/maven_deploy_template.yml@master
    with:
      version: ${{ needs.Version.outputs.next-version }}
      checkout-lfs: true
      maven-opts: '-s ./.github/settings.xml -pl isy-web-lib -Dskip.js.tests=true'
      deploy-url-snapshot: 'https://maven.pkg.github.com/IsyFact/isy-web'
    secrets:
      DEPLOY_SERVER_USER_NAME: ${{ github.actor }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}