name: Release Maven
on:
  release:
    types: [released]

jobs:
  Build:
    uses: IsyFact/isyfact-standards/.github/workflows/maven_build_template.yml@master
    with:
      jdk-version: 8
      maven-opts: '-pl !isy-web-doc -Dskip.js.tests=true'
      checkout-lfs: true
      version: ${{ github.ref_name }}
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

  Deploy:
    needs: [Build]
    uses: IsyFact/isyfact-standards/.github/workflows/maven_deploy_template.yml@master
    with:
      jdk-version: 8
      maven-opts: '-pl !isy-web-doc -Dskip.js.tests=true -P centralRelease'
      checkout-lfs: true
      version: ${{ github.ref_name }}
      deploy-server-id: ossrh
      sbom: true
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      DEPLOY_SERVER_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
