name: Maven Dependency Scan (ORT)
on:
  push:
    branches:
      - develop
      - release/**
      - 'feature/*'
    paths:
      - 'pom.xml'
  workflow_dispatch:

jobs:
  ORT:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/oss_review_toolkit_template.yml@feature/ifs-3956-main_ort
    secrets:
      ANTORA_TRIGGER_TOKEN: ${{ secrets.ANTORA_TRIGGER_TOKEN }}
