name: OSS Review Toolkit
on:
  push:
jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Show paths
        run: cat "/${{ github.workspace }}/ort-data/vulnerability_report.ftl"
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          report-formats: WebApp,StaticHtml,PlainTextTemplate -O PlainTextTemplate=template.path=${{ env.NULL }}https://github.com/IsyFact/isy-web/blob/feature/master_ort/ort-data/vulnerability_report.ftl
